# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    etablissement.manager:
        class: AppBundle\Manager\EtablissementManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    passage.manager:
        class: AppBundle\Manager\PassageManager
        arguments: [@doctrine_mongodb.odm.default_document_manager]

    passage.importer:
        class: AppBundle\Import\PassageCsvImporter
        arguments: [@doctrine_mongodb.odm.default_document_manager, @passage.manager, @etablissement.manager]


