<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Document\Attachement;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * AttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachementRepository extends DocumentRepository {

    public function findLast() {

        return $this->createQueryBuilder()
             ->select('_id', 'updatedAt', 'imageName', 'titre', 'originalName', 'etablissement', 'societe', 'visibleTechnicien', 'ext')
             ->limit(10)
             ->sort(array('_id' => -1))
             ->getQuery()
             ->execute();
    }

    public function findBySociete($societe)
	{
        $attachments = array();
		foreach($this->createQueryBuilder()->select('_id', 'updatedAt', 'imageName', 'titre', 'originalName', 'etablissement', 'societe', 'visibleTechnicien', 'ext')->field('societe')->equals($societe)->getQuery()->execute() as $attachement) {
            $attachments[$attachement->getId()] = $attachement;
        }

        uasort($attachments,array("AppBundle\Document\Attachement", "cmpUpdateAt"));

        return $attachments;
    }

    public function findByEtablissement($etablissement, $date = null)
	{
        $attachments = array();
        $query = $this->createQueryBuilder()->select('_id', 'updatedAt', 'imageName', 'titre', 'originalName', 'etablissement', 'societe', 'visibleTechnicien', 'ext')
                                            ->field('etablissement')->equals($etablissement);

        if ($date) {
            $query->field('updatedAt')->range($date->modify('today'), $date->modify('tomorrow'));
        }

		foreach($query->getQuery()->execute() as $attachement) {
            $attachments[$attachement->getId()] = $attachement;
        }

        uasort($attachments,array("AppBundle\Document\Attachement", "cmpUpdateAt"));

        return $attachments;
    }

	public function findBySocieteAndEtablissement($societe, &$facets = array())
	{
		$qb = $this->createQueryBuilder();
		$attachments = array();
        $facets[$societe->getId()] = 0;
		foreach ($this->findBySociete($societe) as $attachement) {
            $facets[$societe->getId()]++;
			$attachments[$attachement->getId()] = $attachement;
		}

		foreach ($societe->getEtablissements() as $etablissement) {
            $facets[$etablissement->getId()] = 0;
			foreach ($this->findByEtablissement($etablissement) as $attachement) {
                $facets[$etablissement->getId()]++;
				$attachments[$attachement->getId()] = $attachement;
			}
		}

        $facets['total'] = count($attachments);

		uasort($attachments,array("AppBundle\Document\Attachement", "cmpUpdateAt"));

		return $attachments;
	}


}
