<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Tool\RechercheTool;
use AppBundle\Document\Societe;
use MongoDate as MongoDate;
use AppBundle\Manager\EtablissementManager;
use AppBundle\Manager\PassageManager;
use AppBundle\Manager\ContratManager;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends BaseRepository {


  public function findAllDevisForTechnicien(\DateTime $date, $technicien = null, $confirme = true)
  {
    $mongoStartDate = new MongoDate(strtotime($date->format("Y-m-d") . " 00:00:00"));
    $mongoEndDate = new MongoDate(strtotime($date->format("Y-m-d") . " 23:59:59"));
    $queryBuilder = $this->createQueryBuilder('Passage');
    $query = $queryBuilder->field('dateFin')->notEqual(null)
            ->field('dateDebut')->gte($mongoStartDate)
            ->field('dateDebut')->lte($mongoEndDate)
            ->field('rendezVous')->prime(true)
            ->field('techniciens')->prime(true)
            ->field('etablissement')->prime(true);

    if($technicien){
        $queryBuilder->field('techniciens')->equals($technicien->getId());
    }
    $queryBuilder->sort('dateDebut', 'asc');
    $query = $queryBuilder->getQuery();

    $devis = $query->execute();

    return array_filter($devis->toArray(), function ($d) use ($confirme) {
        if ($confirme === true) {
            return $d->getRendezVous()->getRendezVousConfirme() === $confirme;
        }

        // on retourne tous les passages sinon
        return true;
    });
  }

  public function findBySociete(Societe $societe, $withCanceled = false)
  {
    $queryBuilder = $this->createQueryBuilder('Devis');
    $queryBuilder->field('societe')->equals($societe->getId());

    if ($withCanceled === false) {
        $queryBuilder->field('statut')->notEqual(PassageManager::STATUT_ANNULE);
    }

    return $queryBuilder->getQuery()->execute();
  }

  public function findToPlan($secteur = EtablissementManager::SECTEUR_PARIS, \DateTime $dateDebut = null, \DateTime $dateFin) {
      $date = new \DateTime();
      $mongoEndDate = new MongoDate(strtotime($dateFin->format('Y-m-d')));

      $q = $this->createQueryBuilder();
      $q->field('statut')->equals(PassageManager::STATUT_A_PLANIFIER)
              ->field('etablissement')->prime(true)
              ->field('datePrevision')->lte($mongoEndDate);

      if($dateDebut){
        $mongoStartDate = new MongoDate(strtotime($dateDebut->format('Y-m-d')));
        $q->field('datePrevision')->gte($mongoStartDate);

      }

      if ($secteur == EtablissementManager::SECTEUR_PARIS) {
        $q->field('zone')->notEqual(ContratManager::ZONE_SEINE_ET_MARNE);
      } elseif($secteur == EtablissementManager::SECTEUR_SEINE_ET_MARNE) {
         $q->field('zone')->equals(ContratManager::ZONE_PARIS);
      }

      $query = $q->sort('zone', 'asc')->getQuery();

      return $query->execute();
  }

  public function findByQuery($q)
  {
      $q = str_replace(",", "", $q);
      $q = "\"".str_replace(" ", "\" \"", $q)."\"";
      $resultSet = array();
      $itemResultSet = $this->command([
          'find' => 'Devis',
          'filter' => ['$text' => ['$search' => $q]],
          'projection' => ['score' => [ '$meta' => "textScore" ]],
          'sort' => ['score' => [ '$meta' => "textScore" ]],
          'limit' => 100

      ]);
  
          foreach ($itemResultSet as $itemResult) {
              $resultSet[] = array("doc" => $this->uow->getOrCreateDocument('\AppBundle\Document\Devis', $itemResult), "score" => $itemResult['score']);
          }
    
      return $resultSet;
  }
}
