<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Tool\RechercheTool;
use AppBundle\Document\societe;
use AppBundle\Manager\FactureManager;
/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends DocumentRepository {

    public function findAllByContrat($contrat) {

        return $this->createQueryBuilder()
                        ->field('lignes.origineDocument.$id')->equals($contrat->getId())
                        ->getQuery()
                        ->execute();
    }

    public function retrieveAll()
    {
      $qb = $this->createQueryBuilder();
      $qb->hydrate(false);
      $query = $qb->getQuery();
      return iterator_to_array($query->execute());
    }

    public function findByTerms($queryString, $filter = false, $withCloture = false) {
        $terms = explode(" ", trim(preg_replace("/[ ]+/", " ", $queryString)));
        $results = null;
        foreach ($terms as $term) {
            if (strlen($term) < 2) {
                continue;
            }
            $q = $this->createQueryBuilder();
			if (!$withCloture) {
            	$q->field('cloture')->equals(false);
			}
            $q->field('numeroFacture')->notEqual(null);
            if (preg_match('/^[0-9]+\.[0-9]+$/', $term)) {
                $nbInf = $term - 0.0001;
                $nbSup = $term + 0.0001;
                $q->addOr($q->expr()->field('montantTTC')->lt($nbSup)->gt($nbInf))
                  ->addOr($q->expr()->field('montantAPayer')->lt($nbSup)->gt($nbInf));
            } else {
                $q->addOr($q->expr()->field('destinataire.nom')->equals(new \MongoRegex('/.*' . RechercheTool::getCorrespondances($term) . '.*/i')))
                        ->addOr($q->expr()->field('numeroFacture')->equals(new \MongoRegex('/.*' . $term . '.*/i')));
            }
            if($filter && !$withCloture){
                $q->field('cloture')->notEqual(1);
            }
            $factures = $q->limit(1000)->getQuery()->execute();

            $currentResults = array();
            foreach ($factures as $facture) {
                $currentResults[$facture->getId()] = $facture->__toString();
            }

            if (!is_null($results)) {
                $results = array_intersect_assoc($results, $currentResults);
            } else {
                $results = $currentResults;
            }
        }

        return is_null($results) ? array() : $results;
    }

    public function exportOneMonthByDate(\DateTime $dateDebut,\DateTime $dateFin) {

        $q = $this->createQueryBuilder();

        $q->field('dateFacturation')->gte($dateDebut)->lte($dateFin)->sort('dateFacturation', 'asc');
        $q->addAnd($q->expr()->field('numeroFacture')->notEqual(null));
        $query = $q->getQuery();

        return $query->execute();
    }

    public function exportByPrelevements($clients) {
    	$q = $this->createQueryBuilder();
    	$q->addAnd($q->expr()->field('societe')->in($clients));
    	$q->addAnd($q->expr()->field('cloture')->equals(false));
        $q->addAnd($q->expr()->field('montantHT')->gt(0.0));
	$q->addAnd($q->expr()->field('sepa.actif')->equals(true));
        $q->addAnd($q->expr()->field('avoir')->equals(null));
        $q->addAnd($q->expr()->field('inPrelevement')->equals(null));
        $q->addAnd($q->expr()->field('numeroFacture')->notEqual(null));

    	$query = $q->getQuery();
    	return $query->execute();
    }

    public function exportBySocieteAndDate($societe, \DateTime $dateDebut,\DateTime $dateFin) {

        $q = $this->createQueryBuilder();
        $q->field('societe')->equals($societe->getId());
        $q->field('dateFacturation')->gte($dateDebut)->lte($dateFin)->sort('dateFacturation', 'asc');
        $query = $q->getQuery();

        return $query->execute();
    }

    public function findByQuery($q)
    {
        $q = "\"".str_replace(" ", "\" \"", $q)."\"";
    	$resultSet = array();
    	$itemResultSet = $this->getDocumentManager()->getDocumentDatabase('AppBundle:Facture')->command([
    			'find' => 'Facture',
    			'filter' => ['$text' => ['$search' => $q]],
    			'projection' => ['score' => [ '$meta' => "textScore" ]],
    			'sort' => ['score' => [ '$meta' => "textScore" ]],
    			'limit' => 100

    	]);
    	if (isset($itemResultSet['cursor']) && isset($itemResultSet['cursor']['firstBatch'])) {
    		foreach ($itemResultSet['cursor']['firstBatch'] as $itemResult) {
    			$resultSet[] = array("doc" => $this->uow->getOrCreateDocument('\AppBundle\Document\Facture', $itemResult), "score" => $itemResult['score']);
    		}
    	}
    	return $resultSet;
    }

    private function makeBaseFactureRetardDePaiement($nbRelance = null, $societe = null)
    {
      $q = $this->createQueryBuilder();
      $q->field('numeroFacture')->notEqual(null);
      $q->field('cloture')->equals(false);
      $q->field('montantTTC')->gt(0.0);
      if(!is_null($nbRelance)){
        if($nbRelance > 2){
          $q->field('nbRelance')->gte($nbRelance);
        }elseif ($nbRelance == 1 || $nbRelance == 2) {
          $q->field('nbRelance')->equals($nbRelance);
        }elseif ($nbRelance == 0) {
          $q->addOr($q->expr()->field('nbRelance')->equals(null))
            ->addOr($q->expr()->field('nbRelance')->equals(0));
        }
      }
      	if ($societe && !preg_match('/^SOCIETE-[0-9]*$/', $societe)) {
      		$societeRepo = $this->getDocumentManager()->getRepository('AppBundle:Societe');
      		$societeTab = explode(', ', $societe);
      		$societe = $societeRepo->findOneBy(array('identifiant' => $societeTab[count($societeTab)-1]));
        	$q->field('societe')->equals($societe->getId());
      	} elseif ($societe) {
        	$q->field('societe')->equals($societe);
      	}
        $q->sort('dateFacturation', 'desc')->sort('societe', 'asc');
        return $q;
    }

    public function findFactureRetardDePaiement($dateFactureBasse = null, $dateFactureHaute = null, $nbRelance = null, $societe = null, $commerciaux = null){
      $today = new \DateTime();
      if ($dateFactureHaute && $dateFactureHaute instanceof \DateTime) {
          $dateFactureHaute->modify('+1 day');
      }

      // Factures
      $qF = $this->makeBaseFactureRetardDePaiement($nbRelance, $societe);
      $qF->field('dateLimitePaiement')->lte($today);
      if($dateFactureBasse){
        $qF->field('dateFacturation')->gte($dateFactureBasse);
      }
      if($dateFactureHaute){
        $qF->field('dateFacturation')->lte($dateFactureHaute);
      }
      $resultsFacture = $qF->getQuery()->execute();

      // Devis
      $qD = $this->makeBaseFactureRetardDePaiement($nbRelance, $societe);
      $qD->field('numeroDevis')->notEqual(null);
      if($dateFactureBasse){
        $qD->field('dateFacturation')->gte($dateFactureBasse);
      }
      if($dateFactureHaute){
        $qD->field('dateFacturation')->lte($dateFactureHaute);
      }
      if (!$dateFactureHaute) {
          $todayDevis = clone $today;
          $todayDevis->modify("-".FactureManager::DEFAUT_FREQUENCE_JOURS." days");
          $qD->field('dateFacturation')->lt($todayDevis);
      }
      $resultsDevis = $qD->getQuery()->execute();

      $results = array_merge($resultsFacture->toArray(), $resultsDevis->toArray());
        $retards = array();
        foreach($results as $retard) {
          if ($commerciaux) {

            $commerciauxIds=array();
            foreach($commerciaux as $c){
              $commerciauxIds[]=$c->getId();
            }

            if ($retard->getContrat()) {
              if (!$retard->getContrat()->getCommercial()) {
        				continue;
        			} else {
                if (count($commerciauxIds) > 0 && !in_array($retard->getContrat()->getCommercial()->getId(),$commerciauxIds)){
        					continue;
        				}
        			}
            }elseif($retard->getCommercial() && !in_array($retard->getCommercial()->getId(),$commerciauxIds)){
              continue;
            }
        	}
          $retards[$retard->getDateFacturation()->format("YmdHis").$retard->getId()] = $retard;
        }
        krsort($retards);
        return $retards;
    }

    public function getMontantFacture($societe) {
        $command = array();
        $command['aggregate'] = "Facture";
        $command['pipeline'] = array(
            array('$match' => array('societe' => $societe->getId(), "numeroFacture" => array('$ne' => null ))),
            array('$group' => array('_id' => 'somme_montant_facture', 'montantTTC' => array('$sum' => '$montantTTC')))
        );
        $db = $this->getDocumentManager()->getDocumentDatabase(\AppBundle\Document\Facture::class);
        $resultat = $db->command($command);

        return (isset($resultat['result'][0]))? $resultat['result'][0]['montantTTC'] : 0;
    }

    public function findRetardDePaiementBySociete(Societe $societe, $nbJourSeuil = 0){
      return $this->findFactureRetardDePaiement(null, null, null, $societe, null);
    }

}
